Update qvm

diff --git a/qvm b/qvm
--- a/qvm
+++ b/qvm
@@ -7,8 +7,8 @@
 ##
 ## Function to create config file
 ##
-createConfigFile() {
-
+createConfigFile()
+{
 cat 2>/dev/null 1>${CFG} << CONFIG
 ############################################################
 ## ${CMD} configuration
@@ -57,48 +57,48 @@ CFGSTATUS=${?}
 ##
 ## Function to create disk image interactively
 ##
-createDiskImage() {
+createDiskImage()
+{
+read -p "Disk image size (50G) : " IMGSIZE
+[[ ! ${IMGSIZE} ]] && IMGSIZE="50G"
 
-  read -p "Disk image size (50G) : " IMGSIZE
-  [[ ! ${IMGSIZE} ]] && IMGSIZE="50G"
+read -p "File format (qcow2)/raw/vdi/vhdx/vmdk : " IMGFORMAT
+[[ ! ${IMGFORMAT} ]] && IMGFORMAT="qcow2"
 
-  read -p "File format (qcow2)/raw/vdi/vhdx/vmdk : " IMGFORMAT
-  [[ ! ${IMGFORMAT} ]] && IMGFORMAT="qcow2"
+read -p "Name (${IMG}) : " IMGNAME
 
-  read -p "Name (${IMG}) : " IMGNAME
+## User chose disk image name different from what is defined in config
+if [[ ${IMGNAME} ]]; then
+  echo "IMG=${IMG} in configuration file. Edit to set IMG=${IMGNAME}"
+  IMG=${IMGNAME}
+fi
 
-  ## User chose disk image name different from what is defined in config
-  if [[ ${IMGNAME} ]]; then
-    echo "IMG=${IMG} in configuration file. Edit to set IMG=${IMGNAME}"
-    IMG=${IMGNAME}
-  fi
+## Prompt to confirm or redo creating disk image
+echo -n "Create now? or redo/quit (y)/n/q "
 
-  ## Prompt to confirm or redo creating disk image
-  echo -n "Create now? or redo/quit (y)/n/q "
+while true; do
+  read -sn1 INPUT
 
-  while true; do
-    read -sn1 INPUT
+  case ${INPUT} in
+    y|Y|c|C|"") echo; break ;;
+    n|N|r|R) return ;;
+    q|Q) echo; exit ;;
+  esac
 
-    case ${INPUT} in
-      y|Y|c|C|"") echo; break ;;
-      n|N|r|R) return ;;
-      q|Q) echo; exit ;;
-    esac
+done
 
-  done
+## Create disk image or exit on failure
+qemu-img create -f ${IMGFORMAT} "${IMG}" ${IMGSIZE} || exit 1
 
-  ## Create disk image or exit on failure
-  qemu-img create -f ${IMGFORMAT} "${IMG}" ${IMGSIZE} || exit 1
-
-  ## Set success flag
-  IMGSTATUS=1
+## Set success flag
+IMGSTATUS=1
 }
 
 ##
 ## Function to launch QEMU (takes arguments)
 ##
-qemuLaunch () {
-
+qemuLaunch ()
+{
 PS4=""
 set -x
 qemu-system-x86_64 \
